name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Menjalankan setiap hari
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Generate Snake Animation
      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: hanip007
          outputs: dist/snake.svg

      # Push hasil Snake Animation ke repository
      - name: Push Snake Animation to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'GitHub Actions'
          author_email: 'actions@github.com'
          message: "Generate Snake Animation"
          add: dist/snake.svg
